config/routes.rb
Rails.application.routes.draw do
  # remove routes that are not actually utilized
  # except: or only:, etc.
  resources :users
  resources :games, except: [:edit, :index, :show, :update]

  root "home#index"

  get '/game-words' => 'games#words'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words

  validates_presence_of :name
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user

  # validate the existence of the associated user as well:
  validates_presence_of :score, :wpm, :accuracy, :time, :level, :keystrokes # , :user

  def self.order_by_high_scores
    Game.group(:id, :user_id)
        .order(score: :desc)
        .limit(10)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :games # dependent_destroy

  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" ,:small  => "200x200>" }, default_url: "medium/volcanoIcon.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # need this to avoid Arshdeep and arshdeep being saved
  before_save {self.email = email.downcase}

  validates :username, { presence: true, uniqueness: true, length: { maximum: 25 } }
  validates :email, { presence: true, length: { maximum: 105 }, uniqueness: true }

  def high_score
    games.order(Game.arel_table['score'].desc).limit(1).first.score
  end

  def average_wpm
    weighted_wpm = most_recent_games.map { |game| game.wpm * game.time }
    total_wpm = weighted_wpm.reduce(:+)
    total_time = most_recent_games.reduce(0) { |total, game| total + game.time }
    total_wpm / total_time
  end

  def average_accuracy
    weighted_accuracy = most_recent_games.map { |game| game.accuracy * game.keystrokes }
    total_accuracy = weighted_accuracy.reduce(:+)
    total_keystrokes = most_recent_games.reduce(0) { |total, game| total + game.keystrokes }
    total_accuracy / total_keystrokes
  end

  def most_recent_games
    games.order(Game.arel_table['created_at'].desc).limit(10)
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category

  validates_presence_of :text, :points, :x, :y, :level#, :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :authorized?, :current_user

  def login(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorized?(user)
    logged_in? && current_user == user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.save
  end

  def words
    render json: Category.find_by(name: params[:category])
                         .words
                         .where(level: params[:level])
                         .order("random()")
                         .limit(30)
  end

  private

  def game_params
    params.require(:game).permit(:wpm, :score, :accuracy, :time, :level, :keystrokes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username]).try(:authenticate, params[:session][:password])
    if request.xhr?
      if user
        session[:user_id] = user.id
        render status: 200, json: {:user_link => user_path(user)}
      else
        render status: 400, json: {:errors => ["The username and password you entered do not match."]}
      end
    else
      if user
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        @errors = ["The username and password you entered do not match."]
        render "/login"
      end
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    has_secure_password
    before_save {self.email = email.downcase}
    validates :username, presence: true,
                uniqueness: true,
                length: {minimum: 5, maximum: 25}

    validates :password_digest, presence: true,
              uniqueness: {case_sensitive: false},
              length: {minimum: 6}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length:{maximum: 105},
                uniqueness: true,
                format: {with: VALID_EMAIL_REGEX}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @games = Game.order_by_high_scores
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if request.xhr?
      if @user.save
        session[:user_id] = @user.id
        render status: 200, json: {:user_link => user_path(@user)}
      else
        render status: 400, json: {:errors => @user.errors.full_messages}
      end
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        @errors = @user.errors.full_messages
        render new_user_path
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      @errors = @user.errors.full_messages
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/new.html.erb
<div class="game-background">
  <div class="row">
    <div class="col-sm-4">
      <div class="game-rules">
        <ul class="no-dots">
          <li><span class="glyphicon glyphicon-fire"></span> Select Level and Catergory in the drop down menu</li>
          <li><span class="glyphicon glyphicon-fire"></span> Click Start to begin the game</li>
          <li><span class="glyphicon glyphicon-fire"></span> Type the text into the box below the game display</li>
          <li><span class="glyphicon glyphicon-fire"></span> When the word is correctly entered, it will be removed from the game</li>
          <li><span class="glyphicon glyphicon-fire"></span> Press [ENTER] to clear the input box</li>
        </ul>
      </div>
      <div class="level">
        <p>Level:</p>
        <select id="level">
          <option value="1"> Level 1 </option>
          <option value="2"> Level 2 </option>
          <option value="3"> Level 3 </option>
          <option value="4"> Level 4 </option>
          <option value="5"> Level 5 </option>
          <option value="6"> Level 6 </option>
          <option value="7"> Level 7 </option>
          <option value="8"> Level 8 </option>
          <option value="9"> Level 9 </option>
        </select>
      </div>
      <div class="level">
        <p>Category:</p>
        <select id="category">
          <option value="default"> Default </option>
          <option value="animals"> Animals </option>
          <option value="ruby"> Ruby </option>
        </select>
      </div>
    </div>
    <div class="col-la-8">
      <div class="canvas">
        <canvas id="myCanvas" width="500" height="600"></canvas>
        <canvas id="canvasLava" width="500" height="600"></canvas>
        <canvas id="canvasSmoke" width="400" height="300"></canvas>
      </div>
      <input id="inputText" type="text" name="gametext" value="">
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="parallax">
  <div id="section-1" class="parallax-section">
    <section class="go-down"><a href="#instructions"><img alt="go-down" src="arrow.png"  height="52" width="52"> </a></section>
    <div class="parallax-layer parallax-layer-base">
      <div class="full-bg-img flex-center ">
        <h1 class="h1-responsive log"><a href="/games/new"><button id="play-button" type="button" name="Play Now"> Play Now</button></a></h1>
      </div>
    </div>
  </div>
  <div class="container-rules">
    <a name="instructions"></a>
    <div class="features-list">
      <div data-100-bottom-top="transform: translateX(-200px); opacity: 0" data-center-top="transform: translateX(0px); opacity: 1">
        <i class="material-icons">flag</i>
        <p>Increase your typing efficiency in a </p>
        <p>fun and interactive game</p>
      </div>
      <div data-100-bottom-top="transform: translateY(200px); opacity: 0" data-center-top="transform: translateY(0px); opacity: 1">
        <i class="material-icons">flag</i>
        <p>DON'T LET THE WORDS TOUCH THE</p>
        <p>LAVA!!!</p>

      </div>
      <div data-100-bottom-top="transform: translateX(200px); opacity: 0" data-center-top="transform: translateX(0px); opacity: 1">
        <i class="material-icons">flag</i>
        <p>Compete with your friends by</p>
        <p>beating their best score</p>
      </div>
    </div>
  </div>
  <div class="container-rules">
    <div class="body-text">
      <p  data-300-center-top="transform: scale(0.7); opacity: 0" data-300-center-center="transform: scale(1); opacity: 1">
        The goal of this game is to be able to type out the word correctly before it reaches the lava. The player will have 5 lives to start with and will lose a life everytime the word falls into the lava. Once all of the player's lives are used up, the game will be over.
      </p>
      <div id="game-video">
        <img id="gif" src="/game-gif.gif" alt="Loading" title="Loading" />
      </div>
      <p data-100-center-top="transform: scale(0.7); opacity: 0" data-100-center-center="transform: scale(1); opacity: 1">
        Using the box below the game display, type out a single word that you want to input. If the word is correctly typed, the word will explode! Press the [ENTER] key to clear the text box.
      </p>
    </div>
  </div>
  <footer>
    <div class="container">
      <p>The Lava Typers : &nbsp;
        <a href="https://github.com/jdollete" rel="author"> Allain Dollete </a> &nbsp; |&nbsp;
        <a href="https://github.com/arsy209" rel="author"> Arshdeep Singh </a> &nbsp;| &nbsp;
        <a href="https://github.com/asyaasha" rel="author"> Asiya Gizatulina </a> &nbsp;| &nbsp;
        <a href="https://github.com/evanrenaud" rel="author"> Evan Renaud </a> &nbsp;| &nbsp;
        <a href="https://github.com/mr-jungchoi" rel="author"> Jung Choi </a>&nbsp;
      </p>
    </div>
  </footer>
</div>
<script>
  skrollr.init();
</script>

app/views/layouts/_logged_in.html.erb
<ul class="nav navbar-nav navbar-right logout">
  <li class="link-font" ><a  href="/users/<%= current_user.id %>"><%= current_user.username %></a></li>
  <li id="logout_link">
    <a id="logout_link">
      <form action="/logout" method="post" class="login-form-1">
        <input class="form-control" name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input class="form-control" type="hidden" name="_method" value="delete">
        <input id="logout" class="btn btn-link" type="submit" value="Log out">
      </form>
    </a>
  </li>
</ul>

app/views/layouts/_login_register.html.erb
<!-- Registration Form -->
<ul class="nav navbar-nav navbar-right">
  <li>
    <button class="link" data-toggle="modal" data-target="#myModal">
      <span class="link-font">Register</span>
    </button>
  </li>
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <div class="tab-pane" id="Registration">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <form id="register_form" class="form-horizontal" action="/users" method="post">
              <div class="form-group">
                <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                <label for="email" class="col-sm-2 control-label">Email:</label>
                <input class="form-control" type="email" name="user[email]" value=""  placeholder="Email" required>
              </div>
              <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username:</label>
                <input class="form-control" type="text" name="user[username]" value="" placeholder="Username" maxlength="20" required>
              </div>
              <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password:</label>
                <input class="form-control" type="password" name="user[password]" value="" placeholder="Password"  required>
              </div>
              <div class="error_div">
                <ul class="error_register"></ul>
              </div>
              <div class="col-sm-10">
                <input class="btn btn-primary btn-sm" type="submit" name="" value="Register!">
                <button id="registration_cancel" type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</ul>
<!-- Login Drop Down -->
<ul class="nav navbar-nav navbar-right">
  <li>
    <button id="login-button" class="link" data-toggle="modal" data-target="#myModalLogin">
      <span class="link-font">Login</span>
    </button>
  </li>
  <div class="modal fade" id="myModalLogin" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <div class="tab-pane active" id="Login">
              <form id="login_form" class="form-horizontal" action="/sessions" method="post">
                <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                <div class="form-group">
                  <div class="col-sm-10">
                    <label for="username" class="col-sm-2 control-label">Username:</label>
                    <input class="form-control" type="text" name="session[username]" value="">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-10">
                    <label for="password" class="col-sm-2 control-label">Password:</label>
                    <input class="form-control" type="password" name="session[password]" value="">
                  </div>
                </div>
                <div class="error_div">
                  <ul class="error_login"></ul>
                </div>
                <div class="col-sm-10">
                  <input class="btn btn-primary btn-sm" type="submit" name="" value="Login!">
                  <button id="login_cancel" type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</ul>

app/views/layouts/_loginregister.html.erb
<!-- Registration Form -->
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Register<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <form class="" action="/users" method="post">
        <li>
          <div class="">
              <label for="username">Username:</label>
              <input type="text" name="user[username]" value="">
          </div>
        </li>
        <li>
          <div class="">
            <label for="username">Username:</label>
            <input type="text" name="user[username]" value="">
          </div>
        </li>
        <li>
          <div class="">
            <label for="password">Password:</label>
            <input type="text" name="user[password]" value="">
          </div>
        </li>
        <li>
          <div class="">
            <input type="submit" name="" value="Register!">
          </div>
        </li>
      </form>
    </ul>
  </li>
</ul>
<!-- Login Drop Down -->
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <form class="" action="/sessions" method="post">
        <li>
          <div class="">
              <label for="username">Username:</label>
              <input type="text" name="sessions[username]" value="">
          </div>
        </li>
        <li>
          <div class="">
            <form class="" action="/sessions" method="post">
              <label for="password">Password:</label>
              <input type="text" name="sessions[password]" value="">
          </div>
        </li>
        <li>
          <div class="">
            <input type="submit" name="" value="Login!">
          </div>
        </li>
      </form>
    </ul>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LavaTyper</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P|NTR" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/skrollr.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><img src="/Asset 2.png" alt="logo" width="120"></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if !logged_in? %>
            <%= render partial: "layouts/login_register" %>
          <% else %>
            <%= render partial: "layouts/logged_in" %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_errors.html.erb
<ul>
  <% if @errors %>
    <% @errors.each do |error| %>
      <li><%= error %></li>
      <% end %>
  <% end %>
</ul>

app/views/users/edit.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 edit-profile">
      <h1>Update your profile</h1>
      <%if @errors%>
        <%@errors.each do|error|%>
          <ul>
            <li><%=error%></li>
          </ul>
        <%end%>
      <%end%>
      <%= form_for(@user) do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <h4><%= f.label :change_user_icon %></h4>
        <%= f.file_field :avatar, as: :file %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<form id="register_form" class="form-horizontal" action="/users" method="post">
  <div class="form-group">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <label for="email" class="col-sm-2 control-label">Email:</label>
    <input class="form-control" type="email" name="user[email]" value=""  placeholder="Email" required>
  </div>
  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username:</label>
    <input class="form-control" type="text" name="user[username]" value="" placeholder="Username" maxlength="20" required>
  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password:</label>
    <input class="form-control" type="password" name="user[password]" value="" placeholder="Password"  required>
  </div>
  <div class="error_div">
    <% if @errors %>
      <ul>
        <% @errors.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="col-sm-10">
    <input class="btn btn-primary btn-sm" type="submit" name="" value="Register!">
    <button id="registration_cancel" type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
  </div>
</form>

app/views/users/show.html.erb
<div class="container profile profile-size">

  <div class="col-sm-12">
    <div id="img-profile" class="col-sm-3 margin-img img-rounded">
      <%= image_tag @user.avatar.url(:small)%>
    </div>
    <div class="text">
      <div class="col-sm-7 well margin-well">
        <%= link_to 'New Game', new_game_path, class:"btn btn-primary btn-danger" %>
        <% if current_user == @user %>
          <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-primary" %>
        <%end%>
        <h1><kbd><%= @user.username %>'s Stats:</kbd></h1>
        <ul>
          <% if @user.games.empty? %>
            <li>High Score:</li>
            <li>Words Per Minute:</li>
            <li>Accuracy:</li>
          <% else %>
            <li>High Score: <%= @user.high_score %></li>
            <li>Average Words Per Minute: <%= @user.average_wpm.round(2) %></li>
            <li>Average Accuracy: <%= @user.average_accuracy.round(2) %>%</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div id="past-score">
    <div class="col-sm-7 well margin-well">
      <h3><kbd><%= @user.username %>'s Previous Scores:</kbd></h3>
      <table class="table table-hover">
        <tr>
          <th>Level</th>
          <th>Score</th>
          <th>Words Per Minute</th>
          <th>Accuracy</th>
        </tr>
        <% if !@user.games.empty? %>
          <% @user.most_recent_games.each do |game| %>
            <tr>
              <td><%= game.level %></td>
              <td><%= game.score %></td>
              <td><%= game.wpm.round(2) %></td>
              <td><%= game.accuracy.round(2) %>%</td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
  <div id="global-score">
    <div class="col-sm-7 well margin-well">
      <h3><kbd>Global High Scores:</kbd></h3>
      <table class="table table-hover">
        <tr>
          <th>Player</th>
          <th>Level</th>
          <th>Score</th>
          <th>Words Per Minute</th>
          <th>Accuracy</th>
        </tr>
        <% @games.each do |game| %>
          <tr>
            <td><%= game.user.username %></td>
            <td><%= game.level %></td>
            <td><%= game.score %></td>
            <td><%= game.wpm.round(2) %></td>
            <td><%= game.accuracy.round(2) %>%</td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>